export const AvatarTheme = {
  avatar: {
    size: 'avatar-size',
    fontSize: 'avatar-placeholder-font-size',
    colors: {
      amber: 'avatar-color-amber',
      blue: 'avatar-color-blue',
      brown: 'avatar-color-brown',
      crimson: 'avatar-color-crimson',
      cyan: 'avatar-color-cyan',
      grass: 'avatar-color-grass',
      green: 'avatar-color-green',
      indigo: 'avatar-color-indigo',
      lime: 'avatar-color-lime',
      mint: 'avatar-color-mint',
      orange: 'avatar-color-orange',
      pink: 'avatar-color-pink',
      plum: 'avatar-color-plum',
      purple: 'avatar-color-purple',
      red: 'avatar-color-red',
      sky: 'avatar-color-sky',
      teal: 'avatar-color-teal',
      tomato: 'avatar-color-tomato',
      violet: 'avatar-color-violet',
      yellow: 'avatar-color-yellow',
    },
  },
};
