export const ColorTheme = {
  color: {
    background: 'color-background',
    surface: 'color-surface',
    surfaceOverlay: 'color-surface-overlay',
    surfaceHover: 'color-surface-hover',
    textPrimary: 'color-text-primary',
    textSecondary: 'color-text-secondary',
    textDisabled: 'color-text-disabled',
    textLink: 'color-text-link',
    border: 'color-border',
    icon: 'color-icon',
    iconSecondary: 'color-icon-secondary',
    iconDisabled: 'color-icon-disabled',
    attention: 'color-attention',
    attentionBlue: 'color-attention-blue',
    pin: 'color-pin',
    pinHover: 'color-pin-hover',
    pinActive: 'color-pin-active',
    pinDisconnected: 'color-pin-disconnected',
  },
};
