export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function DashboardLayout({ children }: { children: React.ReactNode }) {
  return children;
}
