name: CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

jobs:
  typecheck:
    runs-on: buildjet-32vcpu-ubuntu-2004
    steps:
      - uses: actions/checkout@v2
      - run: yarn install --frozen-lockfile --prefer-offline
      - run: yarn typecheck
      - run: yarn build
  test-functions:
    runs-on: buildjet-32vcpu-ubuntu-2004
    defaults:
      run:
        working-directory: functions
    steps:
      - uses: actions/checkout@v2
      - run: yarn install --frozen-lockfile --prefer-offline
      - run: yarn build
      - run: yarn test
