name: CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize]

jobs:
  typecheck:
    runs-on: buildjet-32vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v2
      - run: yarn install --frozen-lockfile --prefer-offline
      - run: yarn typecheck
      - run: yarn build
  test-functions:
    runs-on: buildjet-32vcpu-ubuntu-2204
    defaults:
      run:
        working-directory: functions
    steps:
      - uses: actions/checkout@v2
      - run: yarn install --frozen-lockfile --prefer-offline
      - run: yarn build
      - run: yarn test
        env:
          FIREBASE_TEST_SERVICE_ACCOUNT: '${{ secrets.FIREBASE_TEST_SERVICE_ACCOUNT }}'
  test-core:
    runs-on: buildjet-32vcpu-ubuntu-2204
    defaults:
      run:
        working-directory: packages/@collabkit/core
    steps:
      - uses: actions/checkout@v2
      - run: yarn install --frozen-lockfile --prefer-offline
      - run: yarn test
  test-client:
    runs-on: buildjet-32vcpu-ubuntu-2204
    defaults:
      run:
        working-directory: packages/@collabkit/client
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn install --frozen-lockfile --prefer-offline
      - run: yarn test
        env:
          VITE_FIREBASE_TEST_SERVICE_ACCOUNT: ${{ secrets.VITE_FIREBASE_TEST_SERVICE_ACCOUNT }}
  test-e2e:
    timeout-minutes: 60
    runs-on: buildjet-32vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: yarn playwright test
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
